export const tempProducts = [
    {
      id: 1,
      name: 'JJICHRIS JJORIGINAL AM 994',
      brand: 'Jack & Jones',
      brandslug: 'jack&jones',
      category: 'Byxor',
      categoryslug: 'byxor',
      price: '499',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['lightblue', 'black', 'grey', 'white', 'beige'],
      new: true,
      sale: true,
      likes: 102,
    },
    {
      id: 2,
      name: 'MR530SG Shoe',
      brand: 'New Balance',
      brandslug: 'newbalance',
      category: 'Skor',
      categoryslug: 'skor',
      price: '1099',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['black', 'grey', 'white'],
      new: true,
      sale: true,
      likes: 421,
    },
    {
      id: 3,
      name: 'PJS M Spectre Body Warmer',
      brand: 'Parajumper',
      brandslug: 'parajumper',
      category: 'Jackor',
      categoryslug: 'jackor',
      price: '3499',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['black'],
      new: true,
      sale: false,
      likes: 134,
    },
    {
      id: 4,
      name: 'PJS M Spectre Body Warmer',
      brand: 'Parajumper',
      brandslug: 'parajumper',
      category: 'Jackor',
      categoryslug: 'jackor',
      price: '3499',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['black'],
      new: true,
      sale: false,
      likes: 247,
    },
    {
      id: 5,
      name: 'PJS M Spectre Body Warmersdf asdfsdf ',
      brand: 'Parajumper',
      brandslug: 'parajumper',
      category: 'Jackor',
      categoryslug: 'jackor',
      price: '3499',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['black'],
      new: false,
      sale: false,
      likes: 612,
    },
    {
        id: 6,
        name: 'Tröja',
        brand: 'Jack & Jones',
        brandslug: 'jack&jones',
        category: 'Tröjor',
        categoryslug: 'trojor',
        price: '499',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['lightblue', 'black', 'grey', 'white', 'beige'],
        new: false,
        sale: true,
        likes: 301,
      },
      {
        id: 7,
        name: 'MR5230SG Shoe',
        brand: 'New Balance',
        brandslug: 'newbalance',
        category: 'Skor',
        categoryslug: 'skor',
        price: '1099',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black', 'grey', 'white'],
        new: false,
        sale: true,
        likes: 395,
      },
      {
        id: 8,
        name: 'Tröja',
        brand: 'Parajumper',
        brandslug: 'parajumper',
        category: 'Tröjor',
        categoryslug: 'trojor',
        price: '3499',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: false,
        sale: false,
        likes: 324,
      },
      {
        id: 9,
        name: 'tshirt1',
        brand: 'Parajumper',
        brandslug: 'parajumper',
        category: 'T-shirt',
        categoryslug: 'tshirt',
        price: '3499',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: false,
        sale: false,
        likes: 79,
      },
      {
        id: 10,
        name: 'tshirt2 ',
        brand: 'Parajumper',
        brandslug: 'parajumper',
        category: 'T-shirt',
        categoryslug: 'tshirt',
        price: '399',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: true,
        sale: true,
        likes: 53,
      },
      {
        id: 11,
        name: 'GEL-QUANTUM 360 VII - Running Shoes',
        brand: 'Asics',
        brandslug: 'asics',
        category: 'Skor',
        categoryslug: 'skor',
        price: '1900',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        imageBig: 'https://via.placeholder.com/380xs380.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: false,
        slide: true,
        sale: false,
        likes: 389,
      },
      {
        id: 12,
        name: 'Lost Temple - Double printed T-Shirt',
        brand: 'Quiksilver',
        brandslug: 'quiksilver',
        category: 'T-shirt',
        categoryslug: 'tshirt',
        price: '350',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        imageBig: 'https://via.placeholder.com/380xs380.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: false,
        slide: true,
        sale: false,
        likes: 192,
      },
      {
        id: 13,
        name: 'Eastport - Utility Jacket',
        brand: 'Levis',
        brandslug: 'levis',
        category: 'Jackor',
        categoryslug: 'jackor',
        price: '2000',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        imageBig: 'https://via.placeholder.com/380xs380.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: false,
        slide: true,
        sale: false,
        likes: 55,
      },
      {
        id: 14,
        name: 'P401 - Oversized Hoodie',
        brand: 'Purple Brand',
        brandslug: 'purplebra d',
        category: 'Jackor',
        categoryslug: 'jackor',
        price: '2500',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        imageBig: 'https://via.placeholder.com/380xs380.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: false,
        slide: true,
        sale: false,
        likes: 237,
      },
  ]