export const tempProducts = [
    {
      id: 1,
      name: 'JJICHRIS JJORIGINAL AM 994',
      brand: 'Jack & Jones',
      category: 'byxor',
      categoryName: 'Byxor',
      price: '499',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['lightblue', 'black', 'grey', 'white', 'beige'],
      new: true,
      sale: true,
      likes: 102,
    },
    {
      id: 2,
      name: 'MR530SG Shoe',
      brand: 'New Balance',
      category: 'skor',
      categoryName: 'Skor',
      price: '1099',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['black', 'grey', 'white'],
      new: true,
      sale: true,
      likes: 421,
    },
    {
      id: 3,
      name: 'PJS M Spectre Body Warmer',
      brand: 'Parajumper',
      category: 'jackor',
      categoryName: 'Jackor',
      price: '3499',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['black'],
      new: true,
      sale: false,
      likes: 134,
    },
    {
      id: 4,
      name: 'PJS M Spectre Body Warmer',
      brand: 'Parajumper',
      category: 'jackor',
      categoryName: 'Jackor',
      price: '3499',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['black'],
      new: true,
      sale: false,
      likes: 247,
    },
    {
      id: 5,
      name: 'PJS M Spectre Body Warmersdf asdfsdf ',
      brand: 'Parajumper',
      category: 'jackor',
      categoryName: 'Jackor',
      price: '3499',
      image: 'https://via.placeholder.com/220xs300.png?text=product+image',
      size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
      color: ['black'],
      new: false,
      sale: false,
      likes: 612,
    },
    {
        id: 6,
        name: 'Tröja',
        brand: 'Jack & Jones',
        category: 'trojor',
        categoryName: 'Tröjor',
        price: '499',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['lightblue', 'black', 'grey', 'white', 'beige'],
        new: false,
        sale: true,
        likes: 301,
      },
      {
        id: 7,
        name: 'MR5230SG Shoe',
        brand: 'New Balance',
        category: 'skor',
        categoryName: 'Skor',
        price: '1099',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black', 'grey', 'white'],
        new: false,
        sale: true,
        likes: 395,
      },
      {
        id: 8,
        name: 'Tröja',
        brand: 'Parajumper',
        category: 'trojor',
        categoryName: 'Tröjor',
        price: '3499',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: false,
        sale: false,
        likes: 324,
      },
      {
        id: 9,
        name: 'tshirt1',
        brand: 'Parajumper',
        category: 'tshirt',
        categoryName: 'T-shirts',
        price: '3499',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: false,
        sale: false,
        likes: 79,
      },
      {
        id: 10,
        name: 'tshirt2 ',
        brand: 'Parajumper',
        category: 'tshirt',
        category: 'T-shirts',
        price: '399',
        image: 'https://via.placeholder.com/220xs300.png?text=product+image',
        size: ['size-1', 'size-2', 'size-3', 'size-4', 'size-5'],
        color: ['black'],
        new: true,
        sale: true,
        likes: 53,
      },
  ]